name: Push request workflow mechanism
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:  
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Tag Version Identification
      id: tag_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
        DRY_RUN: true
        
    - name: Maven Settings XML Creation
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "github", "url": "https://github.com/priyankaj3w/GitWorkflow" }]'
        servers: '[{ "id": "git", "username": "priyankaj3w", "password": "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" }]'
        output_file:  ${{ github.workspace }}/settings.xml
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Maven Build with package version
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }} -B package --file pom.xml
      
    - name: Maven Install
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn install
     
    - run: mkdir artifact && cp target/*.jar artifact
    
    - uses: actions/upload-artifact@v2
      with:
       name: Package
       path: artifact 
        
    - name: Release Creation
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
        
    - name: Tag Creation
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
        CUSTOM_TAG: ${{ steps.tag_version.outputs.new_tag }}

