name: GIt Push WorkfloW
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Tag Identification
      id: tag_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        
    - name: Maven XML Settings File Creation
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "github", "url": "https://github.com/priyankaj3w/GitWorkflow" }]'
        servers: '[{ "id": "github", "username": "priyankaj3w", "password": "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" }]'
        
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
   
    - name: Maven Build
      run: mvn -B package --file pom.xml
    
    - name: Maven Set Package version
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      run: mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }}
    
    - name: Maven Install
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      run: mvn install
   
    - name: Deploy to GitHub
      run: mvn --batch-mode -DuseGitHubPackages=true deploy -s 
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
   
    - name: Release Creation
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
    
    - name: Tag Creation
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        WITH_V: true
        CUSTOM_TAG: ${{ steps.tag_version.outputs.new_tag }}

